- README.md
I think the `getChildContext` is extra when you are trying to use the context.
> README: remove getChildContext in child example

- README.md
@dabit3 (thanks!) updated the README to include an example. This is the same thing except updated:
- getexpo.com -> expo.io
- renamed Exponent to Expo
> Update Documentation to Include Example (updates #37)

- ActionSheet.android.js
Add material design style for Android following material design guidelines
> [Bottom sheets - Components - Material design guidelines](https://material.io/guidelines/components/bottom-sheets.html)
and this is the new look:
> Add material design style for Android

- ActionSheetProvider.js
Intead of having to pass `textStyles` to every call of ActionSheet, this PR allows to specify `textStyles` once and be reused across all instances. Afterall, it will be most-common case to share the look and feel throughout the application.
You can test it like the following:
```
<Provider store={store}>
<ActionSheetProvider textStyle={{fontWeight: '400'}}>
<AppBase />
</ActionSheetProvider>
</Provider>
```
It should be backwards compatible. Also, this pattern would be extensible for other options that could be shared across action sheets.
Edits, considerations, corrections, are more than welcome.
> Allows Android textStyle to be declared at the Provider

- README.md
- src/context.ts
- src/index.ts
If you don't want the hook, could we export the context so I can add a hook in my own code?
> feat: add useActionSheet hook

- package.json
- src/connectActionSheet.tsx
- tsconfig.json
- yarn.lock
Fixes #125 
Hoist statics was removed when this repo moved to typescript by some reason. I have added it back.
> Hoist statics on components with connected action sheet

- src/ActionSheet/ActionGroup.tsx
On Android with `showSeparators` enabled when rendering the first separator after the option, the generated key was "0" (and not "separator-0"), which is the same key as the optionn row key, so React complained about a duplicate key.
> Android: fix duplicate separator key when key arg == 0

- example/App.tsx
- src/connectActionSheet.tsx
- src/context.ts
- src/index.ts
- src/types.ts
When using connectActionSheet, component props shoud have Context.
So need to type `showActionSheetWithOptions: (options:
ActionSheetOptions, callback: (i: number) => void) => void;` many times.
Context is exported, but it is too common name and cant import from
`'@expo/react-native-action-sheet'`.
> Export ActionSheetContext

- src/ActionSheet/index.ios.tsx
- src/ActionSheet/index.tsx
I'm using this library with react-native-navigation, and when we use an [overlay](https://wix.github.io/react-native-navigation/#/docs/top-level-api?id=showoverlaylayout-) to show in an app notification, the ActionSheetProvider blocks any touches to the screen below, even when we set the `interceptTouchOutside` option of the overlay to false. This PR fixes this and allows touches to pass through to below.
> Allow pointer events to pass through containing view

- README.md
- example/ShowActionSheetButton.tsx
- src/ActionSheet/ActionGroup.tsx
- src/ActionSheet/index.tsx
- src/types.ts
On Android, surprisingly, separator and text styles were configurable but not the background. This PR solves this issue by adding a new prop `containerStyle`. Help to replace default `#ffffff` background on a dark theme UI.
> Android: container style configurable (background)

- src/ActionSheet/index.ios.tsx
Android and web optional Options not available on IOS but when users use its work perfectly on web and Android but crash on IOS, Now This issue is fixed in this commit.
> fix(Android-Only options Crash on IOS): IOS Crash on Android Options

- src/ActionSheet/index.ios.tsx
- src/types.ts
https://facebook.github.io/react-native/docs/actionsheetios#showactionsheetwithoptions
You can view the usage on this question (and answer) of mine 
https://stackoverflow.com/questions/57356674/how-to-use-the-anchor-option-for-ipad-in-react-natives-actionsheetios
This is what this option does. It's not working at the moment in this library.
> Add anchor option for iPads

- README.md
- example/App.tsx
- example/ShowActionSheetButton.tsx
This adds a `withAnchor` option to `ShowActionSheetButton` to demo how the anchor works. Also updated the readme.
> chore: ipad anchor in example app

- README.md
- example/App.tsx
- example/ShowActionSheetButton.tsx
- src/ActionSheet/index.tsx
- src/types.ts
https://github.com/expo/react-native-action-sheet/issues/164
https://youtu.be/4aJ8T-M6RR0
Yeap, added.
> Wrap ActionSheet with a Modal

- README.md
- src/ActionSheet/ActionGroup.tsx
- src/ActionSheet/index.tsx
- src/types.ts
Hi there - love this library but have run into some trouble with Android screen reader support:
- Action sheet items don't have a role assigned; "button" is a good fit I think - iOS reads them as buttons
- The rest of the app is still accessible behind the action sheet :(
I didn't see existing issues for these (especially the second one), and can open if desired!
This changes adds the Android-focused prop `importantForAccessibility="yes"` to the sheet while it's being rendered, as well as `"no-hide-descendants"` to the wrapped app content while the sheet is open. This ensures that only the action sheet content is accessible until it gets closed. This requires the app content to be wrapped in a new `<View>`, because there's no guarantee that the user is passing in something that takes …
> Improvements to Android accessibility

- README.md
- src/ActionSheet/ActionGroup.tsx
- src/ActionSheet/index.tsx
- src/types.ts
Closes issue https://github.com/expo/react-native-action-sheet/issues/150
> Add destructiveColor option

- README.md
- src/ActionSheet/index.ios.tsx
- src/types.ts
This PR adds the `userInterfaceStyle` option for iOS.
It can be set to `light` or `dark`, otherwise the default system style will be used.
See https://reactnative.dev/docs/actionsheetios#showactionsheetwithoptions
fix #197
> feat: add `userInterfaceStyle` option for iOS

- README.md
Fixed the badge on README as the badge url for previous slack expo was broken, and the previous link (https://slack.expo.io/) redirects you to the discord invitation link.
> docs: replace slack badge with discord badge

- src/ActionSheet/ActionGroup.tsx
- src/ActionSheet/index.ios.tsx
- src/types.ts
This PR adds support for providing multiple indices to the `destructiveIndex` option.
This is [already supported in ActionSheetIOS](https://github.com/facebook/react-native/pull/18254). Please note that React Native's type definitions are not updated and it seems that `number[]` is not a valid type for `destructiveIndex`. You can easily test it and see that it actually works though.
I have also added support for multiple destructive indices on Android.
Resolves #25.
> Allow multiple destructive indices

- src/types.ts
> fix: use correct callback type allowing for undefined `i`

- README.md
Refs #241 
Prettier format is now included in ESLint checks, so the `yarn fmt` command has been removed, but I have missed the guide in Readme file, sorry about that!
> chore: update Readme after lint stack bump

- src/ActionSheetProvider.tsx
Currently, the Object that is passed into the `value` prop of the provider is generated on each render. This causes each subscriber of `useActionSheet` to re-render, unnecessarily.
This can also cause issues for any dependency arrays or PureComponents that are including `showActionSheetWithOptions`.
This PR will stabilize the identity of the `value`, so it won't change.
I'm not sure if the `getContext` function is necessary. I kept it in there in case it's being used somewhere that I can't see.
> Stabilize the identity of the Provider value

- src/connectActionSheet.tsx
This avoids importing hoist-non-react-statics in the built d.ts file causing errors when using typescript with esModuleInterop = false
> Added return type to connectActionSheet

- src/connectActionSheet.tsx
The modification addresses an issue where react-navigation does not accept Screen components with props other than route and navigation, creating a problem since Screen components passing through connectActionSheet demand the showActionSheetWithOptions prop as dictated by ActionSheetProps.
The value of showActionSheetWithOptions defined in ActionSheetProps is already set within the connectActionSheet function, rendering it unnecessary in the return type. By removing ActionSheetProps from the function's output, we prevent the passing of redundant props and streamline the type definition of components involved.
> Fix connectActionSheet to exclude ActionSheetProps from return type

- src/ActionSheet/TouchableNativeFeedbackSafe.tsx
Custom action sheet currently has no touch feedback on iOS. [`Platform.Version`](https://reactnative.dev/docs/platform#version) as a number and [`TouchableNativeFeedback`](https://reactnative.dev/docs/touchablenativefeedback) are Android only. Updated the `select` to reflect this.
Edit: Noticed there was actually feedback when the iOS version doesn't include a patch number (e.g. simulator with 17.4 vs my device with 17.5.1) and could be coerced into a number in the `Platform.Version <= 20` condition. But that should only be for android anyway
> fix: show touch feedback on iOS when using custom action sheet
